/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class clicker */

#ifndef _Included_clicker
#define _Included_clicker
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     clicker
 * Method:    MessageBoxA
 * Signature: (ILjava/lang/String;Ljava/lang/String;I)I
 */
JNIEXPORT jint JNICALL Java_clicker_MessageBoxA
  (JNIEnv *, jclass, jint, jstring, jstring, jint);

#ifdef __cplusplus
}
#endif
#endif
